### ISSUE TITLE
Versions releases

### ISSUE THREAD

**Issue by Volodymyr-13** [drewmccormack/SwiftCloudDrive#13]
Hey!

Thanks for this package! But could you please release it via versions? Since Xcode really badly working with **Branch** type. 

![Screenshot 1](https://github.com/user-attachments/assets/7be8a933-a64a-4315-8993-93e8a61917f0)

For example, when even I click - update packages to latest versions - it's not or using some cache..  old code.. happened many time with me and I already reported this.

Anyway, versions working much stable!

**Comment by drewmccormack** [comment]
There are already versions. Just change Branch to the option for up to next major release, and put in 1.0.0 as the version. The current version is 1.3.x, and Xcode should already choose it.

**Comment by Volodymyr-13** [comment]
Thanks! But usually I see releases here, and you just only release this first release. 
Also, I'm subscribing and getting notifications then. And so for this repo I didn't get it, until now, since first like release) 

![Screenshot 1](https://github.com/user-attachments/assets/4aa53fa1-acb7-4e36-b4a3-76362ab94f53)
![Screenshot 2](https://github.com/user-attachments/assets/15ea1921-9cb2-47f7-9721-e82b2bd46d8b)

**Comment by drewmccormack** [comment]
OK, will try to remember to do it. But note that I do make the tags which is what Xcode uses. Xcode doesn’t use the releases at all.Kind regards,DrewOn 10 Aug 2024, at 19:15, Volodymyr-13 ***@***.***> wrote:﻿
Thanks! But usually I see releases here, and you just only release this first release.
Also, I'm subscribing and getting notifications then. And so for this repo I didn't get it, until now, since first like release)
Screenshot.1.png (view on web)
Screenshot.2.png (view on web)
