### ISSUE TITLE
Missing an expected key: 'NSPrivacyCollectedDataTypes'

### ISSUE THREAD

**Issue by Volodymyr-13** [drewmccormack/SwiftCloudDrive#14]
Hey,

just a minor bug or even not a bug. 
This is just a new requirement, so a PrivacyInfo.xcprivacy file should be added. Thanks! 

![Screenshot](https://github.com/user-attachments/assets/15cdd469-3894-49e6-9c31-ebac931f001b)

**Comment by drewmccormack** [comment]
I've pushed up version 1.4.2, which includes that key with an empty array. Hopefully that solves it.

The PrivacyInfo was already there, it just didn't have that particular key.

**Comment by Volodymyr-13** [comment]
> I've pushed up version 1.4.2, which includes that key with an empty array. Hopefully that solves it.
> 
> The PrivacyInfo was already there, it just didn't have that particular key.

Thank you for a quick resolution. One thing, I can't see this release under https://github.com/drewmccormack/SwiftCloudDrive/releases 

Since I'm using SPM exact version, so I can't specify this version so far..

Thanks!

**Comment by drewmccormack** [comment]
I haven’t added a release yet, but you shouldn’t need that for SPM. SPM works via the tags, and the new tag should be there.Kind regards,DrewOn 7 Oct 2024, at 12:15, Volodymyr-13 ***@***.***> wrote:﻿

I've pushed up version 1.4.2, which includes that key with an empty array. Hopefully that solves it.
The PrivacyInfo was already there, it just didn't have that particular key.

Thank you for a quick resolution. One thing, I can't see this release under https://github.com/drewmccormack/SwiftCloudDrive/releases
Since I'm using SPM exact version, so I can't specify this version so far..
Thanks!

**Comment by Volodymyr-13** [comment]
> I haven’t added a release yet, but you shouldn’t need that for SPM. SPM works via the tags, and the new tag should be there.

Ahh okay yes, but what is doesn't work is when I set a notification status for this repo to Releases - I will not know that a new version arrived. So this would be really nice if you could release it in Releases. 

As example, I subscribed to such notifications in most popular repos to monitor new versions, since I'm using Exact Version option to manually update each repo. So releases play crucial role for me personally. Thanks!
